### ISSUE TITLE
Invalid IRI identifier when resource name contains points

### ISSUE THREAD

**Issue by maria-grigorieva** [eddieantonio/node-sparql-client#11]
Hi, 
I have a problem accessing data by resource IRI, which contains points. 
For example, in SPARQL`` something like ?dataset
in javascript code for client
.query(...)
.bind('dataset', 'data10_7TeV.00152166.physics_MinBias.merge.ESD.r1647_p306_tid194488_00') 
...
This causes Error: Invalid IRI Identifier

**Comment by eddieantonio** [comment]
Hello!

Thanks for providing the offending identifier. It appears that the the client thinks this is an IRI, whereas it appears to be simply a string. Is this correct?

**Comment by maria-grigorieva** [comment]
when I execute sparql query from simple string, like this:
```
var sparql_str = `select ?datasetID WHERE { <http://<ontology>/datasets/data10_7TeV.00152166.physics_MinBias.merge.ESD.r1647_p306_tid194488_00> <some_prefix>:hasDatasetID ?datasetID . }`;
```
and then 

`client
.query(sparql_str)
.execute(function (error, data) {...});`
- everything fine. 

I'm not sure what is the reason, but I can't bind this identifier "data10_7TeV.00152166.physics_MinBias.merge.ESD.r1647_p306_tid194488_00". 

Here is the error message: 
```
sparql-client-2/lib/iri.js:51
        throw new Error('Invalid IRI identifier');

Error: Invalid IRI identifier
    at Function.IRI.createFromObject (/Users/Maria/MegaPanDA/DKC/NodeJS/DKBFrontEnd/node_modules/sparql-client-2/lib/iri.js:51:15)
    at createTermFromObject (/Users/Maria/MegaPanDA/DKC/NodeJS/DKBFrontEnd/node_modules/sparql-client-2/lib/term/index.js:88:20)
    at createTerm (/Users/Maria/MegaPanDA/DKC/NodeJS/DKBFrontEnd/node_modules/sparql-client-2/lib/term/index.js:77:20)
    at Function.create (/Users/Maria/MegaPanDA/DKC/NodeJS/DKBFrontEnd/node_modules/sparql-client-2/lib/term/index.js:60:12)
    at prepareBinding (/Users/Maria/MegaPanDA/DKC/NodeJS/DKBFrontEnd/node_modules/sparql-client-2/lib/query.js:126:21)
    at Object.Query.bind (/Users/Maria/MegaPanDA/DKC/NodeJS/DKBFrontEnd/node_modules/sparql-client-2/lib/query.js:31:34)
    at res.render.title (/Users/Maria/MegaPanDA/DKC/NodeJS/DKBFrontEnd/routes/index.js:101:9)
    at WaterfallOver (/Users/Maria/MegaPanDA/DKC/NodeJS/DKBFrontEnd/routes/index.js:158:5)
    at /Users/Maria/MegaPanDA/DKC/NodeJS/DKBFrontEnd/routes/index.js:97:6
    at report (/Users/Maria/MegaPanDA/DKC/NodeJS/DKBFrontEnd/routes/index.js:151:13)
```
